Add functionality for activating the star icon
pgoulding/idea-box pull request #26
Opened 2019-04-07 18:30 UTC by ebenezerjay

I've still got to get it saved to storage. And i am not sure why we lost the hover state? Any ideas? I had to change the svg tag to an img tag in the template.

2019-04-07 22:42 UTC, rumizen requested changes
Awesome work Ebenezer, thanks for getting all this functionality done! The logic on the startChange function looks perfect. Pat and I were thinking we might be able to refactor some of the eventListener stuff so that it happens within our cardClone eventListener (that's where we have the other buttons firing from). Let's also make sure we have the changeStar method being called from the starChange function (starIcon.changeStar). Let us know your thoughts on the changes!

2019-04-08 02:03 UTC, ebenezerjay commented
Refactor the functions being called in the anonymous function? 
Yeah, this commit was just for the star being clicked on in the dom, not for saving in local storage (sorry, I could have been more specific with the message). I had started something in the idea.js file, but hadn't really worked it out at the point. I spent awhile with my mentor trying to get the activated star to save into storage. Not able to get it to work though.

2019-04-08 22:43 UTC, rumizen approved these changes

2019-04-08 22:43 UTC, pgoulding approved these changes

2019-04-08 22:43 UTC, merged